apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: web
data:
  my.cnf: |
    [mysqld]
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    default-authentication-plugin=mysql_native_password
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: web
type: Opaque
data:
  # Replace these with your actual base64 encoded values
  # echo -n "your_root_password" | base64
  mysql-root-password: cm9vdHBhc3N3b3Jk
  mysql-user: YXV0aG56X3VzZXI=
  mysql-password: YXV0aG56X3Bhc3N3b3Jk
