apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring
data:
  alloy.yaml: |
    logging {
      level = "info"
    }

    discovery.kubernetes "pods" {
      role = "pod"
    }

    loki.write "default" {
      endpoint {
        url = "http://grafana-loki:3100/loki/api/v1/push"
      }
    }

    loki.source.kubernetes "pods" {
      targets    = discovery.kubernetes.pods.targets
      forward_to = [loki.write.default.receiver]
    }
