apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: monitoring
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
            http:
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/traces
    compactor:
      compaction:
        block_retention: 48h
    query_frontend:
      search:
        backend: local