apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: web
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "Cors": {
        "AllowedOrigins": [
          "http://localhost:5173",
          "http://app.local"
        ]
      },
      "ServiceEndpoints": {
        "DeviceCommunication": "http://device-communication.dau.svc.cluster.local",
        "DeviceProxy": "http://device-proxy.dau.svc.cluster.local",
        "Auth": "http://auth-service.web.svc.cluster.local"
      }
    }
