apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: default
type: Opaque
stringData:
  connection-string: "Server=mysql.default.svc.cluster.local;Port=3306;Database=LoomDB;User=loom-user;Password=loom-password;"