apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrator
  namespace: db 
spec:
  template:
    spec:
      containers:
      - name: migrator
        image: localhost:5000/migrator:latest
        env:
        - name: DBNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: database
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user
        - name: DBPASS
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
      restartPolicy: Never
  backoffLimit: 1