apiVersion: v1
kind: Service
metadata:
  name: grafana-loki
  namespace: monitoring
spec:
  selector:
    app: grafana-loki
  ports:
    - port: 3100
      targetPort: 3100
      protocol: TCP
  type: ClusterIP
