apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-communication
  namespace: dau
  labels:
    app: device-communication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-communication
  template:
    metadata:
      labels:
        app: device-communication
    spec:
      containers:
      - name: device-communication
        image: localhost:5000/device-communication:latest  # Updated image name
        imagePullPolicy: Always  # Changed to Always to ensure we get updates
        ports:
        - containerPort: 80
          name: grpc
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
